### ISSUE TITLE
Keeps on getting NullPointerException on ref/dosync programs?

### ISSUE THREAD

**Issue by xRayWx** [alain-picard/clojure-training#22]
Hello,

I am just trying to write a seemingly simple ref/dosync program, however I keep getting the NullPointerException in various ways of implementing it, heres one of the example, what am I missing?

````
(def warrior (ref {:hit-point {:current 15 :total 40} :inventory {:healing-potion 0}}))
(def preist (ref {:hit-point {:current 30 :total 30} :inventory {:healing-potion 1}}))

(defn heal-up [healer taker]
  (dosync
   (alter healer (dec (get-in healer [:inventory-potion])))
   (alter taker (+ (get-in taker [:hit-point :current]) 15))))

(heal-up preist warrior) ;; getting the exception from calling this

(println @preist)
(println @warrior)
````

**Comment by privisi** [comment]
Couple of things I've noticed
1. `(alter healer (dec (get-in healer [:inventory-potion])))` 
:inventory-potion seems to be a misspell 
2. in order to use get or get-in on a reference you must first 
`(deref warrior)` or `@warrior`
This is probably causing the null error as you are returning the reference itself rather than it's internal values
3. Alter does not update or assoc directly, you must pass in a function to do this
For example
`(alter magician assoc :magic 1000)`
`(alter mario update :lives dec)`
Refer to docs to work out how to structure the arguments

**Comment by xRayWx** [comment]
Thanks a lot, let me give that a try again.
